### ISSUE TITLE
nav-item component

### ISSUE THREAD

**Issue by joeel561** [Borsforce/tindev_frontend#7]
![image](https://user-images.githubusercontent.com/16187979/108605528-d92f5f00-73b4-11eb-9f2e-6779040c0b35.png)

https://projects.invisionapp.com/prototype/tindev-cklc91x3v00jg74011dd7p3wm/play/19fdb945

**Comment by Cheety** [comment]
@joeel561 Da du ja das neue Baselayout mit den nested routes machen wolltest, soll ich dann in dem Baselayout das Navbar anfertigen und implementieren, oder machst du das dann direkt mit in einem Rutsch?

**Comment by Cheety** [comment]
Issue wurde indirekt durch Joeel erledigt
